config:
  partial_parse: true
snowflake:
  outputs:
    dev:
      account: xw69208.us-east-2.aws
      database: CANDIDATE_SANDBOX
      password: v5W77(ho
      role: AGREENBURG_ROLE
      schema: AGREENBURG
      threads: 2
      type: snowflake
      user: AGREENBURG
      warehouse: CANDIDATE_WH
  target: dev
