version: 2

models:
  - name: mart_customer_lifetime_value
    description: Average daily amount spent per customer

    columns:
      - name: customer_id
        description: "Primary key"
        tests:
          - unique
          - not_null

      - name: average_daily_spend
        description: "Average dollar amount spent per day since sign up."